<a href="https://colab.research.google.com/github/Analia-Rivera/-Ejercicios/blob/main/Copia_de_Notebook5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

  # importar numpy
  import numpy as np

In [ ]:
  #1 Arreglos de cero de longitud 12
  array_ceros= np.zeros(12)
  print (array_ceros)
  len(array_ceros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


12

In [ ]:
  #2 Arreglos de longitud 10 con ceros y un 10 en posicion 5
  array_cdiez= np.zeros(10)
  array_cdiez[5]=10
  print (array_cdiez)




[ 0.  0.  0.  0.  0. 10.  0.  0.  0.  0.]


In [ ]:
  #3 Arreglo del 10 al 49
  array_rango= np.arange(10,50)
  print (array_rango)



[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
  #4 Arreglo 2d de shape (3,3) que tenga los numeros del 0 al 8
  array_2d = np.arange (0,9)
  array_2d = array_2d.reshape (3,3)
  print (array_2d)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
  #5 Arreglo numeros aleatorios de longitud 100 y obtener media y varianza
  array_aleatorio = np.random.rand (100)
  print (array_aleatorio)


[6.99087229e-01 5.35369146e-01 6.90985228e-01 8.06755380e-01
 8.60862015e-01 7.80884896e-01 4.50014944e-01 1.26916673e-01
 8.28365962e-01 4.56153487e-01 9.48903427e-03 8.40825674e-01
 4.44404794e-01 1.62693803e-01 4.94300126e-01 3.51859357e-04
 7.23544742e-01 3.01559037e-01 6.77589851e-01 5.52422575e-02
 7.27105290e-01 8.20663595e-01 5.58505818e-01 8.43608976e-03
 3.72952977e-01 2.37159378e-01 9.58546410e-01 5.54105032e-01
 8.70405908e-01 2.14934833e-01 3.16438735e-02 4.16502075e-01
 3.66312963e-01 3.73638417e-01 1.67540738e-01 1.84497026e-02
 9.25588307e-01 2.03567485e-01 9.03659086e-01 6.51825405e-01
 4.71267710e-02 9.54836860e-01 7.25065315e-01 4.94177678e-01
 6.04210225e-01 1.12454847e-01 5.25534303e-02 7.78695567e-01
 4.99404961e-02 8.55566418e-01 5.34135604e-01 9.72846516e-01
 5.96777710e-01 1.45750147e-01 2.50938739e-01 4.84870258e-01
 2.26787590e-01 7.24580985e-01 9.35624111e-01 3.20065420e-01
 7.36132352e-01 6.37557836e-01 9.22029012e-01 1.35682819e-02
 5.03343227e-01 9.852496

In [ ]:
      #media y varianza
      media = np.mean (array_aleatorio)
      print (media)
      varianza= np.var (array_aleatorio)
      print (varianza)

0.5393996405976317
0.08886370383857858


In [ ]:
  #6 Media de una arreglo usando np.sum
  suma = np.sum (array_aleatorio)
  print (suma)
  nro_elementos = len (array_aleatorio)
  media =suma/nro_elementos
  print (media)


53.93996405976317
0.5393996405976317


In [ ]:
  #7 calcular varianza de un arreglo usando np.sum y np.mean
  varianza2 = np.sum ((array_aleatorio-np.mean(array_aleatorio))**2)/len(array_aleatorio)
  print (varianza2)





0.08886370383857858


In [ ]:
  #8 Array de nros aleatorios usando np.random.randn
  array_aleatorio2 = np.random.randn (50)
  print (array_aleatorio2)

[-0.80801275 -0.84113735 -1.9604771  -0.14061594  0.9596112   0.85395296
  0.09969811  0.61485228 -1.8117468  -1.65250182  0.21354154 -0.41576229
 -1.49778628  1.19057459  0.94111779 -1.71245882 -0.97895573 -0.5382835
 -0.53293462  1.1741985   0.80158022 -0.39360265  0.39927439  0.59503173
  1.00033309  0.32906877  0.05712066 -1.32569233 -0.58249587 -1.0600578
 -0.0974581  -0.19295495 -0.24826576  0.41702905  1.6133187  -0.74091092
  0.09317682 -1.35157198 -1.79633869  1.3484662   0.59539737  0.2850553
  0.514449   -0.41754705 -0.81116895 -0.2004804   0.88167442  0.49300535
 -0.53314526 -1.50323916]
